# -*- mode: ruby -*-
# vi: set ft=ruby :

#
# Vagrantfile provided by gradle-plugin-devtool
#

PROJECT_NAME = ENV['PROJECT_NAME'] || File.basename(File.expand_path(File.dirname(__FILE__)))

#
# Environment variables that can be overriden on vagrant up
#
ANSIBLE_GALAXY = ENV['ANSIBLE_GALAXY'] == 'false' ? false : true
VM_NAME = ENV['VM_NAME']
VM_CPUS = ENV['VM_CPUS'] || 4
VM_CPU_CAP = ENV['VM_CPU_CAP'] || 100
VM_MEMORY = ENV['VM_MEMORY'] || 8192
VM_GUI = ENV['VM_GUI'] == 'false' ? false : true
VB_GUEST = ENV['VB_GUEST'] == 'true' ? true : false
HTTP_PROXY = ENV['HTTP_PROXY']
HTTPS_PROXY = ENV['HTTPS_PROXY']
NO_PROXY = ENV['NO_PROXY']
OPENSHIFT_PORT_HOST = ENV['OPENSHIFT_PORT_HOST'] || 8443
TESTING = ENV['VAGRANT_TESTING'] == 'true' ? true : false

boxes = [
  {
  :name => "centos",
  :box => "boxcutter/centos7-desktop",
  :cpu => VM_CPU_CAP,
  :ram => VM_MEMORY,
  :primary => false,
  :syncfolder_type => "none",
  :private_ip => "10.0.2.16"
  }
]

Vagrant.configure("2") do |config|

  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vbguest.auto_update = VB_GUEST
  end

  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :box
  end

  if Vagrant.has_plugin?("vagrant-proxyconf")
    if(HTTP_PROXY.nil? || HTTP_PROXY.empty?)
      config.proxy.enabled = false
    else
      config.proxy.http = HTTP_PROXY
      config.proxy.https = HTTPS_PROXY
      config.proxy.no_proxy = NO_PROXY
    end
  end

  boxes.each do |box|
    config.vm.define box[:name], primary: box[:primary] do |vms|
      vms.vm.box = box[:box]

      if TESTING
        ANSIBLE_DRY_RUN = '--check'
      else
        ANSIBLE_DRY_RUN = ''
        vms.vm.network "forwarded_port", guest: 8443, host: OPENSHIFT_PORT_HOST  # Openshift console
      end

      @syncfolder_type = 'virtualbox'
      if Vagrant::Util::Platform.windows? then
        syncfolder_type = 'nfs'
      end
      vms.vm.synced_folder '../', '/vagrant', type: syncfolder_type , disabled: false

      vms.vm.provider "virtualbox" do |v|
        unless VM_NAME.to_s.strip.empty?
          #Required for testkit testing to cleanup VMs
          v.name = VM_NAME
        end
        v.gui = VM_GUI
        v.cpus = VM_CPUS
        v.customize ["modifyvm", :id, "--cpuexecutioncap", box[:cpu]]
        v.customize ["modifyvm", :id, "--memory", box[:ram]]
        v.customize ["modifyvm", :id, "--ioapic", "on"]
        v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        v.customize ['modifyvm', :id, '--cableconnected1', 'on']
      end

      vms.vm.provider "vmware_workstation" do |v|
        v.gui = VM_GUI
        v.vmx["memsize"] = box[:ram]
        v.vmx["numvcpus"] = VM_CPUS
      end

      vms.vm.provision "bootstrap", type: :shell, path: "provision/bootstrap.sh"
      if box[:name].eql? "ubuntu"
        vms.vm.provision "bootstrapUbuntu", type: :shell, path: "provision/bootstrap_ubuntu.sh"
      elsif box[:name].eql? "centos"
        vms.vm.provision "bootstrapCentos", type: :shell, path: "provision/bootstrap_centos.sh"
      end
      if ANSIBLE_GALAXY
        vms.vm.provision "ansibleGalaxy", type: :shell, path: "provision/ansible_galaxy.sh", args: ['/vagrant/' + PROJECT_NAME + '/provision']
      end
      vms.vm.provision "ansiblePlaybook", type: :shell, inline: "ANSIBLE_STDOUT_CALLBACK=debug ansible-playbook --become -i 'localhost.localdomain,' -c local /vagrant/#{PROJECT_NAME}/provision/playbook.yml #{ANSIBLE_DRY_RUN} -v"

    end
  end

end
