---
- name: Install roles
  become: yes
  become_user: root
  become_method: sudo
  hosts: 
    - all
  pre_tasks:
    - name: Gathering facts
      setup:
  roles:
    - role: openshift
      tags: openshift
    - role: devtools
      name: devtools
      devtools_update_packages: yes
      devtools_user: vagrant
      devtools_password: vagrant
      devtools_group: vagrant
      devtools_ansible_enabled: false
      devtools_vagrant_enabled: false
      devtools_dep_virtualbox_enabled: false
      tags: devtools
    - role: openshift_client
      name: openshift_client
  tasks:
    - include: ../tests/inc_tests.yml 
  environment:
    http_proxy: "{{ lookup('env','http_proxy') }}"
    HTTP_PROXY: "{{ lookup('env','HTTP_PROXY') }}"
    https_proxy: "{{ lookup('env','https_proxy') }}"
    HTTPS_PROXY: "{{ lookup('env','HTTPS_PROXY') }}"
    NO_PROXY: "{{ lookup('env','NO_PROXY') }}"
    no_proxy: "{{ lookup('env','no_proxy') }}"