---
# Centos specific tests.

- name: Test git checked out correctly.
  shell: git branch
  args:
    chdir: "{{ workDir }}/{{ item.name }}"
  with_items: "{{ projects }}"
  register: gitbranch
  when: 
    - item.enabled | bool
    - item.project != projectTypeMssql
    - clone_modules | bool
  tags: 
    - testgit
    - test

- debug: 
    msg: "item={{item}}"
    verbosity: 2
  with_items: "{{gitbranch.results}}"
  when: 
    - gitbranch.results is defined
    - clone_modules | bool
  tags: 
    - testgit
    - test
      
- name: Check git checked out correctly
  fail:
    msg: "Failed. A branch called {{ item.item.repoVersion }} is expected"
  when: 
    - item.stdout is defined
    - item.stdout.find("* {{ item.item.repoVersion }}") == -1
    - item.item.project != 'mssql'
    - item.item.enabled | bool
    - clone_modules | bool
  with_items: "{{ gitbranch.results }}"
  tags: 
    - testgit
    - test