---
- name: Enable openshift port forwarding from host to guest to access services in OpenShift
  hosts: localhost
  vars_files:
    - vars.yml

  tasks:       
    - debug:
        var: workDir
      tags: debug
    - debug:
        var: projectDir
      tags: debug
    - debug:
        var: projects
      tags: debug
        
    - name: Login in OpenShift
      shell: "oc login --insecure-skip-tls-verify=true -u {{ username }} -p {{ password }} {{ openshift }}"
      tags:
        - openshift
        - login

    - name: Forward ports
      shell: "((nohup oc port-forward $(oc get pods | grep {{ item.name }} | grep -i running | grep -v build | grep -v deploy | awk '{print $1}') {{ item.port }} {{ item.port - 2000 }} {{ item.port - 3000 }} 1>/dev/null 2>&1 &)&)"
      register: command_result
      ignore_errors: yes
      with_items: "{{ projects }}"
      when:
        - item.enabled | bool
      tags:
        - portforward

    # TODO Test for mssql portforward
    - name: Test port forwards
      shell: "curl http://127.0.0.1:{{ item.port }}/{{ item.endpoint }}/manage/info"
      register: command_result
      with_items: "{{ projects }}"
      when:
        - item.enabled | bool
        - item.project == projectTypeSpringboot
      failed_when: "'Connection refused' in command_result.stderr"
      tags:
        - portforward
        - testportforward

#     - debug: 
#         msg: "item.item={{item.item}}, item.stdout={{item.stdout}}, item.changed={{item.changed}}"
#         verbosity: 2
#       with_items: "{{curlport.results}}"
#       tags: 
#         - testportforward
#         - portforward
          